# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ProjectUtility',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/ProjectUtility',
                'lib_path': 'ProjectUtility'},
  'syms': { 'ProjectUtility.core': {'ProjectUtility.core.foo': ('core.html#foo', 'ProjectUtility/core.py')},
            'ProjectUtility.dim_red_utility': { 'ProjectUtility.dim_red_utility.foo': ( 'dim_red_utility.html#foo',
                                                                                        'ProjectUtility/dim_red_utility.py')}}}
