"""Flexible utilities for PCA, MDS, and biplots visualizations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_dim_red_utility.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/01_dim_red_utility.ipynb 15
def foo(): pass
